config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  devise_for :users
  resources :events do
    resources :event_registrations, only: [:create], as: "registrations"
    resources :invites, only: [:create]
  end
  resources :users, only: [:show, :index]
  resources :invites, only: [:index, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attending.rb
class Attending < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :event
  validates_uniqueness_of :attendee_id, scope: :event_id
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"

  has_many :attendings, dependent: :destroy
  has_many :attendees, through: :attendings

  has_many :invites, dependent: :destroy

  validates :name, :description, :time, :creator_id, presence: true

  scope :past, -> {where("time <= ?", DateTime.now)}
  scope :upcoming, -> {where("time > ?", DateTime.now)}

  def over?
    time <= DateTime.now
  end
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :inviter, class_name: "User"
  belongs_to :invitee, class_name: "User"
  belongs_to :event
  validates_uniqueness_of :inviter, scope: [:invitee, :event]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event", dependent: :destroy

  has_many :attendings, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendings, source: :event

  has_many :sent_invites, foreign_key: :inviter_id, dependent: :destroy
  has_many :received_invites, foreign_key: :invitee_id, dependent: :destroy

  def incoming_invites
    Invite.where(invitee_id: id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :warning, :danger, :info
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username])
  end
end

app/controllers/event_registrations_controller.rb
class EventRegistrationsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    event_sign_up = Attending.find_or_initialize_by(attendee_id: current_user.id, event_id: params[:event_id])
    if event_sign_up.new_record?
      event_sign_up.save!
      redirect_to root_path, success: "Succesfully joined event!"
    else
      redirect_to root_path, info: "Already joined event!"
    end
  end 
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :create, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
  end

  def new
    @event = current_user.created_events.build
  end
  
  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      current_user.attended_events << @event
      redirect_to events_path
    else
      flash.now[:danger] = @event.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if event.update(event_params)
      redirect_to event_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
  end

  private
  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :time)
  end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!
  before_action :validate_invite_permission, only: :create

  def index
    @invites = current_user.incoming_invites
  end


  def create
    invitee = User.find_by(username: params[:invitee_username])
    if invitee
      invite = Invite.create(inviter_id: current_user.id, invitee_id: invitee.id, event_id: params[:event_id])
      if invite.save
        redirect_back fallback_location: root_path, success: "Succesfully invited #{invitee.name} - @#{invitee.username}"
      else
        redirect_back fallback_location: root_path, danger: "There is already a pending invite to #{invitee.name} - @#{invitee.username}"
      end
    else
      redirect_back fallback_location: root_path, danger: "That user does not exist!"
    end
  end

  def destroy
    #Accepted the invitation
    invite = Invite.find(params[:id])
    if params[:accept] == "1"
      current_user.attended_events << Event.find(invite.event.id)
      flash[:success] = "Succesfully accepted invitation!"
    else
      flash[:success] = "Succesfully declined invitation!"
    end
    invite.destroy
    redirect_to invites_path
  end

  private
  def validate_invite_permission
    redirect_to root_path, info: "You can only invite users to your own events!" unless Event.find(params[:event_id]).creator == current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id]);
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div class="card bg-dark border border-white">
    <div class="card-body">
        <h5 class="card-title font-weight-bold"><%= event.name %></h5>
        <p class="card-subtitle"<%= event.creator %>></p>
        <p class="card-text"><%= event.description %></p>
        <hr class="border-light">
        <p class="card-text">Organizer: <%= event.creator.name %> <small><%= "@#{event.creator.username}" %></small></p>
        <p class="card-text">Event Time: <%= event.time.to_formatted_s(:long_ordinal) %></p>
    </div>
    <div class="card-footer text-muted">
        <% if event.over? %>
            <%= link_to "Event Over", root_path, class: "btn btn-danger disabled", "aria-disabled": true, tabindex: '-1' %>
        <% elsif user_signed_in? && current_user.attended_events.include?(event) %>
            <%= link_to "Attending", root_path, class: "btn btn-primary disabled", "aria-disabled": true, tabindex: '-1' %>
        <% else %>
            <%= link_to "Attend", event_registrations_path(event), method: :post, class: "btn btn-primary"%>
        <% end %>
        <% if is_show %>
            <%= link_to "View", event_path(event), class: "btn btn-primary"%>
        <% end %>
    </div>
</div>
    

app/views/events/_user.html.erb
<li class="list-group-item bg-dark d-flex justify-content-between">
    <span class="d-flex align-items-center">
        <%= attendee.name %>
        <small class="ml-1"><%= "@#{attendee.username}"%></small>
    </span>
    <%= link_to "View Profile", user_path(attendee), class: "btn btn-info"%>
</li>

app/views/events/index.html.erb
<div class="container">
    <% if @events.exists? %>

        <div class="row justify-content-center mb-5">
            <h1 class="font-weight-bold mb-5 bg-success p-3 rounded">Upcoming Events</h1>
            <div class="card-columns">
                <%= render partial: "event", collection: @events.upcoming, locals: {is_show: true}%>
            </div>
        </div>

        <div class="row justify-content-center mb-5">
            <h1 class="font-weight-bold mb-5 bg-danger p-3 rounded">Past Events</h1>
            <div class="card-columns">
                <%= render partial: "event", collection: @events.past, locals: {is_show: true}%>
            </div>
        </div>
        
    <% else%>
        <div class="jumbotron bg-dark">
            <h1 class="display-4">Organize An Event!</h1>
            <p class="lead">There are currently no events on this website. Be the first one to organize an event!</p>
            <hr class="my-4 border border-secondary">
            <p>Invite your friends to this website to stay up to date with the latest events!</p>
        </div>
    <% end %>
</div>

app/views/events/new.html.erb
<div class="container bg-dark pt-3 pb-3 rounded border border-secondary">
    <div class="row justify-content-center">
        <div class="col-10">
            <h2 class="font-weight-bold">Organize Event</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-10">
            <%= form_with model: @event, local: true do |f| %>
                <div class="form-group">
                    <%= f.label :name, "Event name" %>
                    <%= f.text_field :name, class: "form-control", required: true%>
                </div>
                <div class="form-group">
                    <%= f.label :description, "Event description"%>
                    <%= f.text_area :description, class: "form-control", required: true%>
                </div>

                <div class="form-group">
                    <%= f.label :time, "Event time" %>
                    <%= f.datetime_select :time, required: true%>
                </div>

                <%= f.submit "Organize", class: "btn btn-primary"%>
            <% end %>
        </div>
    </div>
</div>

app/views/events/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-5">
            <%= render partial: "event", locals: {event: @event, is_show: false} %> 
            <% if @event.creator == current_user && !@event.over? %>
                <%= form_with url: event_invites_path(@event), method: :post do %>
                    <div class="input-group mt-3">  

                        <%= text_field_tag :invitee_username, "", placeholder: "Invite your friends", class: "form-control bg-dark text-light"%>
                        <div class="input-group-append">
                            <%= submit_tag "Invite", class: "btn btn-success"%>
                        </div>
                    </div>

                <% end %>
            <% end %>
        </div>
        <div class="col-7">
            <div class="card bg-dark text-light">
                <div class="card-header border-bottom border-primary">
                    <h2 class="mb-0 font-weight-bold">
                        <% if @event.attendees.exists? %>
                            Attendees
                        <% else %>
                            No Attendees Currently
                        <% end %>
                    </h2>
                </div>
                <ul class="list-group">
                    <%= render partial: "user", collection: @event.attendees, as: :attendee %>
                </ul>
            </div>
        </div>
    </div>
</div>

app/views/invites/_invite.html.erb
<li class="list-group-item d-flex bg-dark text-light align-items-center justify-content-between">
    <span class="font-weight-bold"><%= invite.event.name %></span>
    <span><%= "From: #{invite.inviter.name}" %></span>
    <nav>
        <%= link_to "View", event_path(invite.event), class: "btn btn-primary"%>
        <%= link_to "Accept", invite_path(invite, accept: "1"), method: :delete, class: "btn btn-success"%>
        <%= link_to "Decline", invite_path(invite, accept: "0"), method: :delete, data: {confirm: "Are you sure you want to decline?"}, class: "btn btn-danger"%>
    </nav>
</li>

app/views/invites/index.html.erb
<div class="container text-light">
    <div class="row justify-content-center mb-4">
        <h1 class="font-weight-bold">Incoming Invites</h1>
    </div>
    <div class="row justify-content-center">
        <div class="col-10">
            <ul class="list-group">

                <% if @invites.exists? %>
                    <%= render partial: "invite", collection: @invites %>
                <% else %>
                    <li class="list-group-item d-flex align-items-center bg-dark text-light lead">There are no incoming invites currently...</li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventOrganizer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    

    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <%= link_to "EventOrg", root_path, class: "navbar-brand"%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="toggle navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li><%= link_to "Organize Event", new_event_path, class: "btn btn-light"%></li>
                <% if user_signed_in? %>
                    <%= link_to "Edit Profile", edit_user_registration_path(current_user), class: "btn btn-warning" %>
                    <%= link_to invites_path, class: "btn btn-info" do %>
                        Invites
                        <span class="badge badge-light"><%= current_user.incoming_invites.count %></span>
                    <% end %>
                    <%= link_to current_user.name, user_path(current_user), class: "btn btn-primary" %>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-danger"%>
                <% else %>
                    <li><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary "%></li>
                    <li><%= link_to "Sign in", new_user_session_path, class: "btn btn-primary "%></li>
                <% end %>
            </ul>
        </div>
    </nav>
    
    <body class="main-background text-light">
    <% if flash[:success] %>
        <div class="alert alert-success"><%= flash[:success] %></div>
    <% end %>
    <% if flash[:danger] %>
        <div class="alert alert-danger"><%= flash[:danger] %></div>
    <% end %>
    <% if flash[:info] %>
        <div class="alert alert-info"><%= flash[:info] %></div>
    <% end %>
    <div class="mt-5">
        <%= yield %>
    </div>
  </body>
</html>

app/views/users/_event.html.erb
<li class="list-group-item bg-dark d-flex justify-content-between">
    <span class="d-flex align-items-center font-weight-bold"><%= event.name %></span>
    <%= link_to "View", event_path(event), class: "btn btn-primary"%>
</li>

app/views/users/show.html.erb
<div class="container">
    <div class="row justify-content-center mb-3">
        <h1 class="font-weight-bold"><%="#{@user.name}'s Profile"%> <small class="text-light"><%="@#{@user.username}"%></small></h1>
    </div>

    <div class="row justify-content-center mb-3">
        <div class="col-10">
        
            <div class="card">
                <div class="card-header bg-primary">
                    <h4 class="font-weight-bold card-text">Organized Events</h4>
                </div>
                <ul class="list-group list-group-flush">
                    <% if @user.created_events.exists? %>
                        <%= render partial: "event", collection: @user.created_events, as: :event%>
                    <% else %>
                        <li class="list-group-item bg-dark">No Events Organized</li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mb-3">
        <div class="col-10">
        
            <div class="card">
                <div class="card-header bg-success">
                    <h4 class="font-weight-bold card-text">Future Events</h4>
                </div>
                <ul class="list-group list-group-flush">
                    <% if @user.attended_events.where("time > ?", DateTime.now).exists? %>
                        <%= render partial: "event", collection: @user.attended_events.where("time > ?", DateTime.now), as: :event%>
                    <% else %>
                        <li class="list-group-item bg-dark text-warning">No Events Attending</li>
                    <% end %>
                </ul>
            </div>
        </div>  
    </div>

    <div class="row justify-content-center mb-3">
        <div class="col-10">
        
            <div class="card">
                <div class="card-header bg-danger">
                    <h4 class="font-weight-bold card-text">Past Events</h4>
                </div>
                <ul class="list-group list-group-flush">
                    <% if @user.attended_events.where("time <= ?", DateTime.now).exists? %>
                        <%= render partial: "event", collection: @user.attended_events.where("time <= ?", DateTime.now), as: :event%>
                    <% else %>
                        <li class="list-group-item bg-dark text-warning">No Events Attended</li>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</div>